# ������������
server:
    # ��������HTTP�˿ڣ�Ĭ��Ϊ8081
    port: 8081
    servlet:
        context-path: /
spring:
    datasource:
        url: jdbc:mysql://8.130.29.166:3306/recommend?useSSL=false
        username: root
        password: gaonimeiA123!
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
